### ISSUE TITLE
[SUGGESTION] Make the towers spawn far less frequently. I loaded up a world and they all spawned in a grid like 200 blocks away. 

### ISSUE THREAD

**Issue by Huyckss** [n643064/BattleTowers#6] opened 2024-10-12 22:15 UTC
title. the towers spawn way too frequently. i want to include this in a personal modpack but it spawns way too many.

**Comment by n643064** [comment] 2024-10-14 22:34
Duplicate of https://github.com/n643064/BattleTowers/issues/4

**Closed as completed by n643064** 2024-10-14 22:34 UTC
